Fix PeriodicVariables2
arcana-lab/gino pull request #20
Opened 2024-09-26 15:07 UTC by dmdlott

NEW HANDLING OF PERIODIC SCCS IN DOALL AND GINO:
- We now break the loop carried dependence of these SCCs by introducing an absolute iteration counter into the loop and directly calculating the SCC value from the counter at each iteration.

HAS A SISTER PR FROM NOELLE, REQUIRES THE SISTER PR

2024-09-27 23:33 UTC, scampanoni commented on src/core/doall/src/DOALL_chunking.cpp
> +    // We have a crummy assumption that periodic vars have only two incoming
Please be consistent with how we write comments.
/*
 * ...
 * /

2024-09-29 23:31 UTC, scampanoni commented on src/core/doall/src/DOALL_chunking.cpp
> +    // get clones of PVSCC vals
What is PVSCC?

2024-09-29 23:32 UTC, scampanoni commented on src/core/doall/src/DOALL_chunking.cpp
> +    /* DD: we choose to not do this and instead replace the whole PVSCC with a
Please remove "DD"

2024-09-29 23:32 UTC, scampanoni commented on src/core/doall/src/DOALL_chunking.cpp
> +    /* DD: we choose to not do this and instead replace the whole PVSCC with a
Also, please follow the comment pattern we have been using throughout the codebase

2024-09-29 23:32 UTC, scampanoni commented on src/core/doall/src/DOALL_chunking.cpp
> +     * DD: there are other options here but we kind of just arbitrarily select
Remove "DD"

2024-09-29 23:32 UTC, scampanoni commented on src/core/doall/src/DOALL_chunking.cpp
> +     * DD: there are other options here but we kind of just arbitrarily select
Please be precise and avoid ambiguous sentences like "we kind of just..."

2024-09-29 23:33 UTC, scampanoni commented on src/core/doall/src/DOALL_chunking.cpp
> +    // If there's some problem in here, consider whether e.g. the initialValue
I didn't get this comment.

2024-09-29 23:33 UTC, scampanoni requested changes
The code looks correct (great job!), but the comments need to be improved.

2024-10-07 19:00 UTC, dmdlott commented
@scampanoni bumping it on gino too

2024-10-07 22:11 UTC, merged